Trim down supported file extensions per OS
conda-forge/spyder-feedstock pull request #183
Opened 2024-08-28 01:53 UTC by ccordoba12

- Spyder is basically a Python based editor, so there's no need to set it as the default for a lot of extensions we don't really support.
- See https://github.com/spyder-ide/spyder/issues/22389 for the problems the previous associations can introduce.

2024-08-28 01:53 UTC, ccordoba12 commented
@mrclary, could you take a look at this one? Thanks!

2024-08-28 02:59 UTC, mrclary commented
Let me take a look at this. I agree that Spyder should not be the default application, but it should be in the "Open with..." context menu and these files should be openable from a Spyder open-file dialogue.

2024-08-28 03:54 UTC, mrclary requested changes
@ccordoba12, I still need to test this PR, but at least the trailing commas in lists need to be removed, otherwise `JSONDecodeError` results.

2024-08-28 03:54 UTC, mrclary commented on recipe/spyder-menu.json
>                          ".pyx",
```suggestion
                        ".pyx"
```
Final list item with "," results in `JSONDecodeError`

2024-08-28 03:54 UTC, mrclary commented on recipe/spyder-menu.json
>                          "text/x-python",
```suggestion
                        "text/x-python"
```
Final list item with "," results in `JSONDecodeError`

2024-08-28 03:54 UTC, mrclary commented on recipe/spyder-menu.json
>                                  "public.python-script",
```suggestion
                                "public.python-script"
```
Final list item with "," results in `JSONDecodeError`

2024-08-28 04:50 UTC, mrclary commented on recipe/spyder-menu.json
>                                  "public.python-script",
```suggestion
                                "public.plain-text",
                                "public.python-script"
```

So, I would retain at least plain-text for macOS. We could retain them all, or add them at the request of users. On macOS, these do not make them default. The absence of them results in the application not included in "Recommended Applications" for opening the file.

<img width="802" alt="Screenshot 2024-08-27 at 9 34 57 PM" src="https://github.com/user-attachments/assets/fff49eb2-3f87-4088-84ed-61ec16edd1c3">

2024-08-30 16:02 UTC, ccordoba12 commented
@mrclary, this is ready for another review.

2024-08-30 16:05 UTC, mrclary approved these changes
Looks good to me; thanks @ccordoba12

2024-08-30 16:21 UTC, merged